/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CallDetailsPlaceholder: typeof import('./src/components/call-history/call-details-placeholder.vue')['default']
    CallDialer: typeof import('./src/components/call-starter/call-dialer.vue')['default']
    CallHistory: typeof import('./src/components/call-history/call-history.vue')['default']
    CallItem: typeof import('./src/components/call-history/call-item.vue')['default']
    CallList: typeof import('./src/components/call-history/call-list.vue')['default']
    CallListFilter: typeof import('./src/components/call-history/call-list-filter.vue')['default']
    CallStarter: typeof import('./src/components/call-starter/call-starter.vue')['default']
    ContactItem: typeof import('./src/components/call-starter/contact-item.vue')['default']
    ContactList: typeof import('./src/components/call-starter/contact-list.vue')['default']
    InputSearch: typeof import('./src/components/call-history/input-search.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineSeperatorDate: typeof import('./src/components/call-history/timeline-seperator-date.vue')['default']
  }
}
