<%-- AWLUICommonAppIncludeWithStrictDocType.inc   -

   Copyright (c) 1992-2020 Dassault Systemes.
   All Rights Reserved.
   This program contains proprietary and trade secret information of MatrixOne,
   Inc.  Copyright notice is precautionary only
   and does not evidence any actual or intended publication of such program

   This file is added to override the default Doctype which is coming from BPS.
--%>

<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">


<%@include file = "../emxUICommonAppNoDocTypeInclude.inc"%>
